package com.dfiles.service;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.json.JSONArray;
import org.json.JSONObject;

import java.io.IOException;
import java.net.ProxySelector;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

/**
 * Turns a plain-English instruction into a bash script using an OpenAI-compatible Chat
 * Completions API. Two backends are supported via {@link AiProvider}: OpenAI's own hosted API,
 * and a local <a href="https://github.com/Mozilla-Ocho/llamafile">Llamafile</a> server — both
 * speak the same request/response JSON shape, so one implementation serves either.
 *
 * <p>The OpenAI API key is read from the {@code OPENAI_API_KEY} environment variable at call
 * time only; it is never stored, cached or logged. The JDK's own {@link HttpClient} is used, so
 * no extra HTTP dependency is needed.
 */
public final class AiScriptService {

    private static final Logger LOGGER = LogManager.getLogger(AiScriptService.class);

    private static final String SYSTEM_PROMPT =
            "You are a bash scripting assistant. Given an instruction, respond with ONLY a complete, " +
            "safe bash script that accomplishes it. Start the script with a #!/usr/bin/env bash shebang " +
            "line and add brief comments for non-obvious steps. Do not wrap the script in markdown code " +
            "fences and do not include any explanation before or after the script — output the script " +
            "content only.";

    /** Used for {@link AiProvider#OPENAI}, which needs the JVM's normal (possibly proxied)
     * internet route. */
    private static final HttpClient CLIENT = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(15))
            .build();

    /** Used for {@link AiProvider#LOCAL_LLAMAFILE}. Explicitly bypasses any system-configured
     * HTTP proxy: unlike browsers, {@link HttpClient} does not exempt localhost from the JVM's
     * default proxy selector, so on a machine with a proxy set, a request to
     * {@code http://localhost:8080} would otherwise be routed through it and fail — even though
     * the same URL works fine from a browser or {@code curl}, which do exempt localhost. */
    private static final HttpClient LOCAL_CLIENT = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(15))
            .proxy(ProxySelector.of(null))
            .build();

    private AiScriptService() {}

    /**
     * Requests a bash script for {@code prompt} from {@code provider}. Blocking — callers must
     * run this off the JavaFX Application Thread.
     *
     * @param prompt   the user's plain-English description of the script they want
     * @param provider which backend to call
     * @return the generated script text, with any markdown code fences stripped and a
     *         {@code # Generated by DFiles using <provider>, model: <model>} comment inserted
     *         after the shebang line (the model name comes from the response itself, not the
     *         request, since that's the actual model that produced the script)
     * @throws IOException if the provider is unreachable, returns a non-200 response, or (for
     *                      {@link AiProvider#OPENAI}) no API key is configured
     * @throws InterruptedException if the calling thread is interrupted while waiting on the request
     */
    public static String generateScript(String prompt, AiProvider provider) throws IOException, InterruptedException {
        String apiKey = System.getenv("OPENAI_API_KEY");
        if (provider.requiresApiKey() && (apiKey == null || apiKey.isBlank())) {
            throw new IOException("OPENAI_API_KEY environment variable is not set");
        }

        JSONObject body = new JSONObject()
                .put("model", provider.getModel())
                .put("temperature", 0.3)
                .put("messages", new JSONArray()
                        .put(new JSONObject().put("role", "system").put("content", SYSTEM_PROMPT))
                        .put(new JSONObject().put("role", "user").put("content", prompt)));

        HttpRequest.Builder requestBuilder = HttpRequest.newBuilder()
                .uri(URI.create(provider.getEndpoint()))
                .timeout(Duration.ofSeconds(60))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(body.toString()));
        if (provider.requiresApiKey()) {
            requestBuilder.header("Authorization", "Bearer " + apiKey);
        }

        HttpClient client = provider == AiProvider.LOCAL_LLAMAFILE ? LOCAL_CLIENT : CLIENT;
        LOGGER.info("Requesting script generation from {} ({} chars prompt)", provider.getDisplayName(), prompt.length());
        HttpResponse<String> response;
        try {
            response = client.send(requestBuilder.build(), HttpResponse.BodyHandlers.ofString());
        } catch (IOException e) {
            String detail = e.getClass().getSimpleName() + (e.getMessage() == null ? "" : ": " + e.getMessage());
            throw new IOException(provider == AiProvider.LOCAL_LLAMAFILE
                    ? "Could not reach the local Llamafile server at " + provider.getEndpoint() + " — is it running? (" + detail + ")"
                    : "Could not reach " + provider.getDisplayName() + ": " + detail, e);
        }

        if (response.statusCode() != 200) {
            LOGGER.error("{} API returned status {}: {}", provider.getDisplayName(), response.statusCode(), response.body());
            throw new IOException(describeError(provider, response.statusCode(), response.body()));
        }

        JSONObject json = new JSONObject(response.body());
        String content = json.getJSONArray("choices")
                .getJSONObject(0)
                .getJSONObject("message")
                .getString("content");
        // The server's own "model" field is more precise than what we requested (e.g. OpenAI
        // resolves an alias like "gpt-4o-mini" to a dated snapshot; Llamafile reports whichever
        // .gguf file it actually loaded, which the fixed AiProvider model name can't know).
        String actualModel = json.optString("model", provider.getModel());
        return addGeneratedByComment(stripMarkdownFences(content), provider, actualModel);
    }

    /** Inserts a comment recording which AI backend and model produced the script, right after
     * the shebang line if there is one (otherwise at the very top). Purely a provenance note for
     * whoever reads the script later — it has no effect on execution. */
    private static String addGeneratedByComment(String script, AiProvider provider, String model) {
        String comment = "# Generated by DFiles using " + provider.getDisplayName() + ", model: " + model;
        int firstNewline = script.indexOf('\n');
        String firstLine = firstNewline == -1 ? script : script.substring(0, firstNewline);
        if (firstLine.startsWith("#!")) {
            String rest = firstNewline == -1 ? "" : script.substring(firstNewline + 1);
            return firstLine + "\n" + comment + "\n" + rest;
        }
        return comment + "\n" + script;
    }

    private static String describeError(AiProvider provider, int statusCode, String body) {
        try {
            JSONObject json = new JSONObject(body);
            if (json.has("error")) {
                Object error = json.get("error");
                String message = error instanceof JSONObject
                        ? ((JSONObject) error).optString("message", body)
                        : String.valueOf(error);
                return provider.getDisplayName() + " API error (" + statusCode + "): " + message;
            }
        } catch (Exception ignored) {
            // fall through to the raw body below
        }
        return provider.getDisplayName() + " API error (" + statusCode + "): " + body;
    }

    private static String stripMarkdownFences(String text) {
        String trimmed = text.strip();
        if (trimmed.startsWith("```")) {
            int firstNewline = trimmed.indexOf('\n');
            if (firstNewline != -1) trimmed = trimmed.substring(firstNewline + 1);
            if (trimmed.endsWith("```")) trimmed = trimmed.substring(0, trimmed.length() - 3);
        }
        return trimmed.strip();
    }
}
